name: Go

on:
  push:
    branches: ["main"]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v4
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        skip-cache: true
    - name: Build
      run: go build -v ./...
    - name: Test
      run: go test *.go
